<template><view class="page">
  <view class="card"><text class="title">预约参数</text><view v-for="field in fields" :key="field.key" class="field"><view><text class="label">{{field.label}}</text><text class="hint">{{field.hint}}</text></view><input v-if="field.type!=='time'" type="number" v-model.number="settings[field.key]"/><picker v-else mode="time" :value="settings[field.key]" @change="settings[field.key]=$event.detail.value"><text>{{settings[field.key]}} ›</text></picker></view><button class="save" @click="save">保存参数</button></view>
  <view class="card"><text class="title">分房优先级</text><view v-for="rule in rules" :key="rule.id" class="rule"><view class="rule-head"><text>{{scene(rule.scene)}} · {{rule.room}}</text><switch :checked="rule.is_enabled" color="#1a6b47" @change="rule.is_enabled=$event.detail.value"/></view><view class="row"><text>优先级</text><input type="number" v-model.number="rule.priority"/><text>容量</text><input type="number" v-model.number="rule.capacity"/></view><picker :range="['共享','独占']" :value="rule.usage_mode==='shared'?0:1" @change="rule.usage_mode=Number($event.detail.value)===0?'shared':'exclusive'"><view class="mode">使用方式：{{rule.usage_mode==='shared'?'共享':'独占'}} ›</view></picker><button class="mini" @click="saveRule(rule)">保存此规则</button></view></view>
</view></template>
<script setup>
import{ref,onMounted}from'vue';import{getRooms,getSettings,saveSettings,updateRoomRule}from'@/api/index.js';const settings=ref({}),rules=ref([]);const fields=[{key:'max_minutes_per_day',label:'单日时长上限（分钟）',hint:'默认240分钟'},{key:'advance_days',label:'可提前预约天数',hint:'包含今天'},{key:'open_hour',label:'开放开始小时',hint:'0-23'},{key:'close_hour',label:'开放结束小时',hint:'1-24'},{key:'slot_minutes',label:'最小时段（分钟）',hint:'建议30'},{key:'cancel_deadline_minutes',label:'取消截止（分钟）',hint:'开始前'},{key:'checkin_grace_minutes',label:'签到宽限（分钟）',hint:'开始后'},{key:'auto_approval_time',label:'自动审批时间',hint:'每日执行',type:'time'},{key:'reminder_minutes',label:'开始提醒（分钟）',hint:'开始前'}];const scene=v=>({study:'自习',meeting:'开会',event:'大型活动',music:'音乐练习'})[v]
async function load(){settings.value=await getSettings();const rooms=await getRooms();rules.value=rooms.flatMap(room=>room.scene_rules.map(rule=>({...rule,room:`${room.room_code} ${room.name}`})))}async function save(){await saveSettings(settings.value);uni.showToast({title:'参数已保存',icon:'success'})}async function saveRule(rule){await updateRoomRule(rule.id,{priority:Number(rule.priority),capacity:Number(rule.capacity),usage_mode:rule.usage_mode,is_enabled:rule.is_enabled});uni.showToast({title:'规则已保存',icon:'success'})}onMounted(load)
</script>
<style scoped>.page{padding:20rpx;background:#f5f6f8;min-height:100vh}.card{background:#fff;border-radius:16rpx;padding:24rpx;margin-bottom:18rpx}.title{display:block;font-size:30rpx;font-weight:700;margin-bottom:12rpx}.field{display:flex;align-items:center;justify-content:space-between;padding:18rpx 0;border-bottom:1rpx solid #eee}.label{display:block;font-size:25rpx}.hint{font-size:20rpx;color:#999}.field input{width:150rpx;text-align:right}.save{margin-top:22rpx;background:#1a6b47;color:#fff}.rule{padding:20rpx 0;border-bottom:1rpx solid #eee}.rule-head,.row{display:flex;align-items:center;justify-content:space-between}.rule-head{font-size:26rpx;font-weight:700}.row{margin-top:12rpx;font-size:22rpx}.row input{width:90rpx;text-align:center;background:#f4f6f5;border-radius:8rpx}.mode{padding:14rpx 0;font-size:23rpx;color:#65736c}.mini{font-size:21rpx;line-height:58rpx}</style>
