<template><view class="page">
  <view v-for="user in users" :key="user.id" class="card"><view class="main"><text class="name">{{user.name}} <text class="role">{{role(user.role)}}</text></text><text>{{user.student_id}} · {{user.class_name}}</text><text>{{user.phone}}</text><view v-for="item in activeRestrictions[user.id]||[]" :key="item.id" class="restriction"><text>{{restrictionLabel(item)}} · {{item.reason}}</text><text class="revoke" @click="revoke(item.id)">解除</text></view></view><button v-if="user.role==='student'" class="restrict" @click="restrict(user)">设置限制</button></view>
</view></template>
<script setup>
import{ref}from'vue';import{onShow}from'@dcloudio/uni-app';import{addRestriction,getRestrictions,getUsers,revokeRestriction}from'@/api/index.js';const users=ref([]),activeRestrictions=ref({});const role=v=>({student:'学生',counselor:'辅导员',admin:'管理员'})[v]||v
const restrictionLabel=item=>item.level==='permanent'?'永久封禁':`${item.level==='temporary'?'临时':'限时'}封禁至 ${item.ends_at?.slice(0,10)}`
async function load(){users.value=await getUsers();const pairs=await Promise.all(users.value.filter(x=>x.role==='student').map(async x=>[x.id,(await getRestrictions(x.id)).filter(r=>r.is_active)]));activeRestrictions.value=Object.fromEntries(pairs)}async function restrict(user){const pick=await new Promise(resolve=>uni.showActionSheet({itemList:['临时封禁1天','限时封禁7天','限时封禁30天','永久封禁'],success:r=>resolve(r.tapIndex),fail:()=>resolve(-1)}));if(pick<0)return;const reason=await new Promise(resolve=>uni.showModal({title:`限制 ${user.name}`,editable:true,placeholderText:'请填写原因',success:resolve}));if(!reason.confirm||!reason.content)return;const options=[['temporary',1],['timed',7],['timed',30],['permanent',null]][pick];await addRestriction(user.id,{level:options[0],days:options[1],reason:reason.content});uni.showToast({title:'限制已生效',icon:'success'});await load()}async function revoke(id){await revokeRestriction(id);uni.showToast({title:'已解除',icon:'success'});await load()}onShow(load)
</script>
<style scoped>.page{padding:20rpx;background:#f5f6f8;min-height:100vh}.card{display:flex;align-items:center;background:#fff;padding:24rpx;border-radius:16rpx;margin-bottom:12rpx}.main{flex:1;display:flex;flex-direction:column;gap:5rpx;font-size:22rpx;color:#87918c}.name{font-size:28rpx;font-weight:700;color:#293c33}.role{font-size:19rpx;padding:3rpx 8rpx;background:#edf2ef;border-radius:6rpx}.restriction{display:flex;justify-content:space-between;padding:10rpx;margin-top:6rpx;border-radius:8rpx;background:#fff0f0;color:#a94343}.revoke{text-decoration:underline;margin-left:12rpx}.restrict{margin:0 0 0 12rpx;font-size:21rpx;line-height:58rpx;background:#a94343;color:#fff}</style>
